src/FavRocks.Site/Models/Home/CreateRequest.cs
namespace FavRocks.Site.Models.Home
{
    public class CreateRequest
    {
        public string Action { get; set; }
        public string Color1 { get; set; }
        public string Color2 { get; set; }
        public string Color3 { get; set; }
        public string Color4 { get; set; }
        public string Color5 { get; set; }
        public string[][] Pixels { get; set; }
    }
}

src/FavRocks.Site/Models/Home/IndexRequest.cs
namespace FavRocks.Site.Models.Home
{
    public class IndexRequest : BaseIndexRequest<IndexRequest>
    {
        public override string Color1 { get; set; } = "ff0000";
        public override string Color2 { get; set; } = "00ff00";
        public override string Color3 { get; set; } = "0000ff";
        public override string Color4 { get; set; } = "ffffff";
        public override string Color5 { get; set; } = "000000";
    }
}

src/FavRocks.Site/ViewModels/Home/IndexResponse.cs
namespace FavRocks.Site.ViewModels.Home
{
    public class IndexResponse
    {
        public IndexResponse()
        {
            for (var i = 0; i < Pixels.Length; i++)
            {
                Pixels[i] = new string[16];

                for (var j = 0; j < Pixels[i].Length; j++)
                {
                    Pixels[i][j] = "transparent";
                }
            }
        }

        public string Color1 { get; set; }
        public string Color2 { get; set; }
        public string Color3 { get; set; }
        public string Color4 { get; set; }
        public string Color5 { get; set; }
        public int ImageHeight { get; set; } = 16;
        public int ImageWidth { get; set; } = 16;
        public string[][] Pixels { get; set; } = new string[16][];
    }
}

src/FavRocks.Site/Controllers/HomeController.cs
using FavRocks.Site.Models.Home;
using FavRocks.Site.ViewModels.Home;
using ImageProcessorCore;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;
using Newtonsoft.Json;
using System;
using System.IO;
using System.IO.Compression;
using System.Text;
using ColorSwatches = FavRocks.Site.Models.ColorSwatches;

namespace FavRocks.Site.Controllers
{
    public class HomeController : Controller
    {
        public HomeController(ISession session)
        {
            this.session = session;
        }

        private readonly ISession session;

        [HttpGet]
        [Route("")]
        public IActionResult Index([FromQuery]IndexRequest model)
        {
            var viewModel = new IndexResponse();

            if (!model.ContainsValidColors())
            {
                throw new Exception("Invalid colors.");
            }

            viewModel.Color1 = model.Color1;
            viewModel.Color2 = model.Color2;
            viewModel.Color3 = model.Color3;
            viewModel.Color4 = model.Color4;
            viewModel.Color5 = model.Color5;

            byte[] rawPixelBoard;

            if (session.TryGetValue("pixelBoard", out rawPixelBoard))
            {
                var pixelBoard = JsonConvert.DeserializeObject<CreateRequest>(Encoding.UTF8.GetString(rawPixelBoard));

                viewModel.Pixels = pixelBoard.Pixels;
            }

            return View(viewModel);
        }

        [HttpPost]
        [Route("")]
        public IActionResult Create(CreateRequest model)
        {
            var pixelBoardModel = JsonConvert.SerializeObject(model);

            session.SetString("pixelBoard", pixelBoardModel);

            if (model.Action == "more")
            {
                var colorSwatchesModel = ColorSwatches.IndexRequest.CreateRequest(
                    color1: model.Color1,
                    color2: model.Color2,
                    color3: model.Color3,
                    color4: model.Color4,
                    color5: model.Color5);

                return RedirectToAction("Index", "ColorSwatches", colorSwatchesModel);
            }
            else
            {
                Image image = new Image(16, 16);

                using (PixelAccessor<Color, uint> pixels = image.Lock())
                {
                    var x = 0;

                    foreach (var row in model.Pixels)
                    {
                        var y = 0;

                        foreach (var column in row)
                        {
                            Color color = Color.Transparent;

                            if (!string.Equals("transparent", column, System.StringComparison.CurrentCultureIgnoreCase))
                            {
                                color = new Color(column);
                            }

                            pixels[y, x] = color;

                            y++;
                        }

                        x++;
                    }
                }

                var imageFile = new MemoryStream();

                image.SaveAsPng(imageFile);

                imageFile.Position = 0;

                var zipArchiveStream = new MemoryStream();
                using (var archive = new ZipArchive(zipArchiveStream, ZipArchiveMode.Create, true))
                {
                    using (var entryStream = archive.CreateEntry("favicon.png").Open())
                    {
                        imageFile.CopyTo(entryStream);
                    }

                    using (var entryStream = archive.CreateEntry("instructions.md").Open())
                    {
                        using (var instructionsStream = System.IO.File.OpenRead("instructions.md"))
                        {
                            instructionsStream.CopyTo(entryStream);
                        }
                    }
                }

                zipArchiveStream.Position = 0;

                return File(zipArchiveStream, "application/zip", "favicon.zip");
            }
        }

        public IActionResult Error()
        {
            return View();
        }
    }
}

src/FavRocks.Site/Controllers/ResetController.cs
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;

namespace FavRocks.Site.Controllers
{
    public class ResetController : Controller
    {
        public ResetController(ISession session)
        {
            this.session = session;
        }

        private readonly ISession session;

        [HttpGet]
        [Route("reset")]
        public IActionResult Index()
        {
            session.Remove("pixelBoard");

            return RedirectToAction("Index", "Home");
        }
    }
}

src/FavRocks.Site/Views/Home/Index.cshtml
@model Home.IndexResponse

@{
    ViewData["Title"] = "Home";
}

@section styles {
    <environment names="Development">
        <link rel="stylesheet" href="~/css/home/index.css" />
    </environment>
    <environment names="Staging,Production">
        <link rel="stylesheet" href="~/css/home/index.min.css" asp-append-version="true" />
    </environment>
    <style>
        .pixel {
            width: @((1.0 / Model.ImageWidth) * 100)%;
        }

        .row {
            height: @((1.0 / Model.ImageHeight) * 100)%;
        }

        .color-selector.color1 + .color-selector-ui {
            background-color: #@Model.Color1;
            color: #@Model.Color1;
        }

        .color-selector.color2 + .color-selector-ui {
            background-color: #@Model.Color2;
            color: #@Model.Color2;
        }

        .color-selector.color3 + .color-selector-ui {
            background-color: #@Model.Color3;
            color: #@Model.Color3;
        }

        .color-selector.color4 + .color-selector-ui {
            background-color: #@Model.Color4;
            color: #@Model.Color4;
        }

        .color-selector.color5 + .color-selector-ui {
            background-color: #@Model.Color5;
            color: #@Model.Color5;
        }

        .pixel .pixel-color-container.color1 > .pixel-color-container-selector[type="radio"]:checked + .pixel-color-container-ui {
            background-color: #@Model.Color1;
        }

        .pixel .pixel-color-container.color2 > .pixel-color-container-selector[type="radio"]:checked + .pixel-color-container-ui {
            background-color: #@Model.Color2;
        }

        .pixel .pixel-color-container.color3 > .pixel-color-container-selector[type="radio"]:checked + .pixel-color-container-ui {
            background-color: #@Model.Color3;
        }

        .pixel .pixel-color-container.color4 > .pixel-color-container-selector[type="radio"]:checked + .pixel-color-container-ui {
            background-color: #@Model.Color4;
        }

        .pixel .pixel-color-container.color5 > .pixel-color-container-selector[type="radio"]:checked + .pixel-color-container-ui {
            background-color: #@Model.Color5;
        }
    </style>
}

<ul class="instructional-wizard">
    <li class="instructional-wizard-step">Select colors below.</li>
    <li class="instructional-wizard-step">Select cells in the grid.</li>
    <li class="instructional-wizard-step">Remove mistakes.</li>
    <li class="instructional-wizard-step">Explore additional colors.</li>
    <li class="instructional-wizard-step">Download your creation!</li>
</ul>

<form id="color-selector" method="post">
    <input type="hidden" name="color1" value="@Model.Color1" />
    <input type="hidden" name="color2" value="@Model.Color2" />
    <input type="hidden" name="color3" value="@Model.Color3" />
    <input type="hidden" name="color4" value="@Model.Color4" />
    <input type="hidden" name="color5" value="@Model.Color5" />
    <input type="radio" id="color1" class="color-selector color1" name="color" checked />
    <label class="color-selector-ui" for="color1" title="#@Model.Color1">#@Model.Color1</label>
    <input type="radio" id="color2" class="color-selector color2" name="color" />
    <label class="color-selector-ui" for="color2" title="#@Model.Color2">#@Model.Color2</label>
    <input type="radio" id="color3" class="color-selector color3" name="color" />
    <label class="color-selector-ui" for="color3" title="#@Model.Color3">#@Model.Color3</label>
    <input type="radio" id="color4" class="color-selector color4" name="color" />
    <label class="color-selector-ui" for="color4" title="#@Model.Color4">#@Model.Color4</label>
    <input type="radio" id="color5" class="color-selector color5" name="color" />
    <label class="color-selector-ui" for="color5" title="#@Model.Color5">#@Model.Color5</label>
    <input type="radio" id="color-transparent" class="color-selector transparent" name="color" />
    <label class="color-selector-ui" for="color-transparent" title="Transparent"></label>

    <button class="color-selector-ui" name="action" value="more" title="Explore additional color swatches">🌐</button>

    <div id="pixel-grid">
        <div class="pixels">
            @for (var x = 0; x < Model.ImageHeight; x++)
            {
                <div class="row">
                    Row @(x):
                    <br />
                    @for (var y = 0; y < Model.ImageWidth; y++)
                    {
                        var name = $"pixels[{x}][{y}]";
                        var pixel = Model.Pixels[x][y];

                        <span class="pixel">
                            Column @(y):
                            <label class="pixel-color-container transparent">
                                Transparent
                                <input type="radio" class="pixel-color-container-selector" name="@(name)" value="transparent" checked="@(pixel == "transparent" ? "checked" : null)" />
                                <span class="pixel-color-container-ui"></span>
                            </label>
                            <label class="pixel-color-container color1">
                                @Model.Color1
                                <input type="radio" class="pixel-color-container-selector" name="@(name)" value="@Model.Color1" />
                                <span class="pixel-color-container-ui"></span>
                            </label>
                            <label class="pixel-color-container color2">
                                @Model.Color2
                                <input type="radio" class="pixel-color-container-selector" name="@(name)" value="@Model.Color2" />
                                <span class="pixel-color-container-ui"></span>
                            </label>
                            <label class="pixel-color-container color3">
                                @Model.Color3
                                <input type="radio" class="pixel-color-container-selector" name="@(name)" value="@Model.Color3" />
                                <span class="pixel-color-container-ui"></span>
                            </label>
                            <label class="pixel-color-container color4">
                                @Model.Color4
                                <input type="radio" class="pixel-color-container-selector" name="@(name)" value="@Model.Color4" />
                                <span class="pixel-color-container-ui"></span>
                            </label>
                            <label class="pixel-color-container color5">
                                @Model.Color5
                                <input type="radio" class="pixel-color-container-selector" name="@(name)" value="@Model.Color5" />
                                <span class="pixel-color-container-ui"></span>
                            </label>
                            @if (pixel != "transparent")
                            {
                                <label class="pixel-color-container custom">
                                    @pixel
                                    <input type="radio" class="pixel-color-container-selector" name="@(name)" value="@(pixel)" checked="@(pixel != "transparent" ? "checked" : null)" />
                                    <span class="pixel-color-container-ui" style="background-color: #@(pixel);" title="@(pixel)"></span>
                                </label>
                            }
                            <br />
                        </span>
                    }
                </div>
                <br />
            }
        </div>
        <div id="notice">
            Grid enlarged to show detail. Download image size is @(Model.ImageWidth)x@(Model.ImageHeight) px.
        </div>
        <div id="actions">
            <a asp-action="Index" asp-controller="Reset" id="reset">Reset</a>
            &nbsp;
            <button id="download" class="button">Download</button>
        </div>
    </div>
</form>
<div class="clearfix"></div>